### ISSUE TITLE
Greetings workflow is not working

### ISSUE THREAD

**Issue by eoinhalpin99** [tom-halpin/dallying-with-DALL-E#12]
I submitted a PR to this repository and the greetings GitHub workflow didn't trigger.

**Comment by tom-halpin** [comment]
Thank you @eoinhalpin99, for reporting. I will take a look, feel free to submit a PR if you have time to fix

**Comment by eoinhalpin99** [comment]
Submitted https://github.com/eoinhalpin99/dallying-with-DALL-E/pull/1 to address.

**Comment by tom-halpin** [comment]
ty
